# release:
#   smth: val
dev:
  slim:
    pretty: true
# gds: true

default_locale: ru

i18n:
  en:
    title: >
      Platron - universal system for online payments.
      Online payment system for internet shops. ::  Pay with bank card
  ru:
    agent_fee: Агентский сбор
    amount: Стоимость заказа
    bill_amount: Стоимость заказа
    card_number_error: Ошибка в номере карты
    cardholder: ИМЯ И ФАМИЛИЯ ВЛАДЕЛЬЦА КАРТЫ латиницей
    delay_description: Обработка платежа задерживается по неизвестным причинам,
      просим отслеживать статус платежа в личном кабинете магазина
      или обратиться в службу поддержки.
    exp_date: Укажите срок действия карты
    form_config_error: Неправельные натройки формы
    gds_warning: >
      Внимание! Стоимость билета и сумма агентского сбора будут списаны с
      вашей банковской карты в два этапа!'
    gds_why: Почему так?
    header: Оплата банковской картой
    month_placeholder: M
    pay: Оплатить
    please_wait: >
      Дождитесь завершения операции оплаты по банковской карте.
      По окончанию вы будете перенаправлены на сайт магазина, где завершите процесс покупки.
    total: Итого
    title: >
      Платрон - универсальная система приема платежей на сайте.
      Система электронных платежей для интернет магазинов.
    what_is_it: Что это?
    year_placeholder: Г
    you_pay: Вы оплачиваете

    card_number: Номер карты
    card_number_hint: 14-19 цифр на лицевой стороне карты
    card_exp: Срок действия
    card_exp_hint: Месяц и год срока действия карты
    cardholder: Имя и фамилия владельца карты
    cardholder_placeholder: ЛАТИНИЦЕЙ
    cardholder_hint: Как на лицевой стороне карты. Если на карте нет имени и фамилии, то укажите свои имя и фамилию латинскими буквами.
    cvc_hint: 3 последние цифры на обратной стороне карты
    we_accept: Мы принимаем
    phone_number: Номер телефона
    phone_number_hint: >-
      Номер указывается в международном формате (только цифры).
      Например: 79031234567 или 380445430591
    for_payment_tracking: Нужен для отслеживания статуса платежа
    send_me_email: Прислать на мой e-mail информацию об оплате
    total_with_comission: 'Сумма с комиссией:'
    pay_with_card: Оплатить картой
    postpone_payment: Отложить оплату заказа
    postpone_title: Отложить платеж
    postpone_description: >-
      Укажите email, на который будет выслана ссылка,
      перейдя по которой Вы сможете завершить оплату до {{expire_date}}
    bank_card_title: Безопасная оплата банковской картой
    cancel: Отмена
    send: Отправить
    js_required: Для продолжения включите javascript
    24h: (круглосуточно)
    more: Подробнее
    close: Закрыть
    order_title: Заказ в магазине {{MERCHANT_NAME}}
    order_total: 'Сумма заказа:'
    order_description: 'Описание заказа:'
    suppoer: 'Служба поддержки:'
    provider: Сервис по переводу денежных средств оказывается ООО РНКО «РИБ»
    waiter_title: Процесс оплаты
    please_wait: >-
      Дождитесь завершения операции.
      По окончанию вы будете перенаправлены на сайт магазина, где завершите процесс покупки.
    title: >-
      Платрон - универсальная система приема платежей на сайте.
      Система электронных платежей для интернет магазинов.
    delay_description: >-
      Обработка платежа задерживается по неизвестным причинам,
      просим отслеживать статус платежа в личном кабинете магазина
      или обратиться в службу поддержки.
